name: Build release version

on:
  release:
    types:
      - published

jobs:
  build_project:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -U -B -Dspring.profiles.active=test clean install && cp target/mcp-identityregistry-core-latest.jar docker/
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/maritimeconnectivity/identityregistry
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
